---

stages:
  - build

default:
  image: fedora:latest
  timeout: 3h

variables:
  CMAKE_FLAGS: "-DWITH_SSL=system -DPLUGIN_COLUMNSTORE=NO -DPLUGIN_ROCKSDB=NO -DPLUGIN_S3=NO -DPLUGIN_MROONGA=NO -DPLUGIN_CONNECT=NO -DPLUGIN_TOKUDB=NO -DWITH_WSREP=OFF"

mini-benchmark:
  stage: build
  tags: 
    - benchmark
  variables:
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: normal
  script:
    # Get mini-benchmark script
    - curl -o $CI_PROJECT_DIR/support-files/mini-benchmark.sh https://raw.githubusercontent.com/MariaDB/server/535711055643952df05774ddb0c94858101be5f6/support-files/mini-benchmark.sh
    - chmod +x $CI_PROJECT_DIR/support-files/mini-benchmark.sh
    # Set up ccache
    - yum install -y ccache  # From EPEL
    - source /etc/profile.d/ccache.sh
    - export CCACHE_DIR="$(pwd)/.ccache"; ccache --zero-stats
    # Build and install
    - yum install -y yum-utils eatmydata
    - yum-builddep -y mariadb-server
    - mkdir builddir; cd builddir
    - cmake $CMAKE_FLAGS .. | tee -a ../build.log
    - eatmydata make install -j $(nproc --ignore=2) 2>&1 | tee -a ../build.log
    - export PATH=$PATH:/usr/local/mysql/bin/
    - ccache -s
    - cd $CI_PROJECT_DIR
    # Set up user and directory
    - groupadd mysql
    - useradd -r -g mysql -s /bin/false mysql
    - sudo mkdir -p /var/lib/mysql/
    - sudo chown -R mysql:mysql /var/lib/mysql/
    # Set the socket to where sysbench expects it
    - sed -i '/\[client-server\]/a socket=/var/lib/mysql/mysql.sock' /etc/my.cnf
    # Install server
    - /usr/local/mysql/scripts/mariadb-install-db --user mysql --datadir /var/lib/mysql
    # Start server
    - sudo -u mysql /usr/local/mysql/bin/mariadbd --datadir /var/lib/mysql & sleep 5
    - /usr/local/mysql/bin/mariadb-upgrade -u root
    # Run mini-benchmark
    - yum install -y sysbench procps-ng perf flamegraph flamegraph-stackcollapse-perf util-linux dnf-utils
    - $CI_PROJECT_DIR/support-files/mini-benchmark.sh --perf
    - cp -av $CI_PROJECT_DIR/*/sysbench-run-*.log $CI_PROJECT_DIR/*/metrics.txt $CI_PROJECT_DIR  # Move files one level down so they can be saved as artifacts
  artifacts:
    when: always
    paths:
      - "$CI_PROJECT_DIR/*/sysbench-run-*.log"
    reports:
      metrics:
        - "$CI_PROJECT_DIR/*/metrics.txt"
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - .ccache
